name: mole
channels:
    - https://conda.anaconda.org/kne 
    - https://conda.binstar.org/tlatorre 
    - https://conda.anaconda.org/cjs14
    - https://conda.anaconda.org/menpo
    - jjhelmus
    - soumith
dependencies:
- python=3.5
- numpy==1.11.2
- mkl-service=1.1.2
- joblib==0.9.4
- mako
- tabulate=0.7.5
- termcolor
- scikit-learn
- opencv3=3.1.0
- path.py
- pip:
  - cloudpickle==1.2.1
  - click
  - ipdb==0.11
  - PyOpenGL
  - matplotlib==2.2.2
  - pyprind
  - pip==18.0
  - pyyaml==3.12
  - wheel==0.30.0
  - scipy==1.0.0
  - tensorflow_gpu==1.8.0
  - ipython==6.4.0
  - colorlog==3.1.0
  - cached_property
  - git+https://github.com/Theano/Theano.git@adfe319ce6b781083d8dc3200fb4481b00853791#egg=Theano
  - git+https://github.com/openai/gym.git@385a85fd0c1b26ab1374f208fbb370e22647548d#egg=gym