gym_config:
    render: False
    task_dynamics_list: [0]
    subtask_episode: 3           # the number of episode for each subtask
    subtask_episode_length: 200     # the length of each episode
    task_episode: 100            # the number of the task episode
    seed: 1000                   # seed for all environments
    dynamics_name: [             # name of all environments
        'CartPoleSwingUpEnvCm05Pm05Pl05-v0',
        'CartPoleSwingUpEnvCm05Pm04Pl07-v0',
        'CartPoleSwingUpEnvCm05Pm08Pl05-v0',
        'CartPoleSwingUpEnvCm05Pm08Pl07-v0',
    ]


# MPC controller configuration
mpc_config:
    constraint: True
    prior_safety: False
    optimizer: "Random"             # Random or CEM, # random may need to fix bugs
    Random: # TODO: warning may contain not finished modification
        env: 'swingup'           # 'stable'
        horizon: 25              # how long of the horizon to predict
        popsize: 1000            # how many random samples for mpc
        gamma: 0.99              # reward discount coefficient
        action_low: [-1]           # lower bound of the solution space
        action_high: [1]           # upper bound of the solution space
        action_dim: 1
        max_iters: 20
        num_elites: 50
        epsilon: 0.2
        alpha: 0.01
        init_mean: 0
        init_var: 10
        action_cost: False
        x_dot_cost: False
        particle: 2
    CEM:
        env: 'swingup'
        horizon: 25                # how long of the horizon to predict
        popsize: 200              # how many random samples for mpc
        particle: 2                # number of particles to enlarge
        gamma: 1                   # reward discount coefficient
        action_low: [-1]           # lower bound of the solution space
        action_high: [1]           # upper bound of the solution space
        action_dim: 1
        max_iters: 5
        num_elites: 20
        epsilon: 0.001
        alpha: 0.1
        init_mean: 0
        init_var: 1
        action_cost: True
        x_dot_cost: False


SingleGP_config:
    state_dim: 5                 # dimension of the state space
    action_dim: 1                # dimension of the action space    
    lr: 0.1                      # learning rate of the gaussian process
    gp_iter: 3                   # iteration time of GP


SingleSparseGP_config:
    state_dim: 5                 # dimension of the state space
    action_dim: 1                # dimension of the action space    
    lr: 0.1                      # learning rate of the gaussian process
    gp_iter: 3                   # iteration time of GP


NN_config:
    model_config:
        load_model: False        # If set true, you must specify the model path, otherwise train a new model
        model_path: "./baselines/storage/example.ckpt" # the path to load the model
        state_dim: 5             # environment states
        action_dim: 1            # how many controls we need
        output_dim: 5            # output dim
        hidden_dim: 2            # hidden layer number
        hidden_size: 256         # hidden layer size
    
    training_config:
        n_epochs: 600            # how many epoches to train the dynamic model
        learning_rate: 0.0005     # learning rate
        batch_size: 512
        save_model_flag: False
        save_model_path: "./baselines/storage/exp_1.ckpt" # the path to save the model
        validation_flag: False
        validation_freq: 10      # the frequency of validation
        validation_ratio: 0.2    # ratio of validation set
        exp_number: 1            # experiment number
    
    dataset_config:
        load_flag: False 
        load_path: "./baselines/storage/data_exp_1.pkl"     
        n_max_steps: 1000        # maximum steps per episode
        n_random_episodes: 800   # how many random episodes' data to fit the initial dynamic model
        testset_split: 0.2       # testset's portion in the random dataset, the rest portion is the training set
        n_mpc_episodes: 4        # how many episodes data sampled with the MPC controller
        mpc_dataset_split: 0.5   # mpc dataset's portion in the training set
        min_train_samples: 6000
        n_mpc_itrs: 100          # the number to perform reinforce iteration
        save_flag: False         # set True if you want to save all the dataset
        save_path: "./baselines/storage/data_exp_1.pkl"



NP_config:
    model_config:
        load_model: False           # If set true, you must specify the model path, otherwise train a new model
        model_path: "./baselines/storage/example.ckpt" # the path to load the model
        state_dim: 5                # environment states
        action_dim: 1               # how many controls we need
        output_dim: 5               # output dim
        likelihood_method: 'gp'     # 'gp' like method or 'nn'
        likelihood_value: 'loss'    # negative 'loss' for likelihood 'll'
        sequential: False           # permute the data while training
        virtual_batch: False        # To be updated
        np_hidden_list: [128, 32]         #[1024, 1024, 1024, 1024]
        np_latent_dim: 32
        np_context_max_num: 100
        np_predict_context_num: 100

    training_config:
        n_epochs: 200            # how many epoches to train the dynamic model
        learning_rate: 0.002     # learning rate
        batch_size: 64
        save_model_flag: False
        save_model_path: "np_save_test.ckpt" # the path to save the model
        validation_flag: False
        validation_freq: 100      # the frequency of validation
        validation_ratio: 0.1    # ratio of validation set
